import Head from "next/head";
import React from "react";

function HeadTitle() {
  return (
    <Head>
      <title>Xoon - Photography Portfolio NextJs Template</title>
      <meta charSet="UTF-8" />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
      ></meta>
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="assets/images/sm-logo.svg"
        type="image/gif"
        sizes="20x20"
      />
    </Head>
  );
}

export default HeadTitle;
